#!/bin/sh

##
# atum
##

. /etc/rc.common

StartService() {
  ConsoleMessage "Starting atum service supervision"
  /bin/csh -cf '/sbin/ennead-start &'
}
StopService() {
  ConsoleMessage "Stopping atum service supervision"
  heka -w196 force-stop /service/*
  heka exit /service/*
}
RestartService() {
  return 0
}

RunService "$1"
