name: compile-check

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  compile-check-on-ubuntu:
    strategy:
      matrix:
        runners: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.runners }}
    steps:
    - uses: actions/checkout@v6
    - name: compile-check
      run: package/compile && package/check
  compile-check-on-macos:
    strategy:
      matrix:
        runners: [macos-latest, macos-15, macos-14]
    runs-on: ${{ matrix.runners }}
    steps:
    - uses: actions/checkout@v6
    - name: compile-check
      run: |
        echo 'cc -Xlinker -x' > src/conf-ld
        sed -i '' 's/ -static//' src/Makefile
        package/compile && package/check

  compile-check-on-freebsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: compile-check
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        run: |
          echo 'cc -O2 -Wall' > src/conf-cc
          echo 'cc -s' > src/conf-ld
          package/compile && package/check

  compile-check-on-openbsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: compile-check
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        run: |
          echo 'cc -O2 -Wall' > src/conf-cc
          echo 'cc -s' > src/conf-ld
          package/compile && package/check

  compile-check-on-netbsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: compile-check
      uses: vmactions/netbsd-vm@v1
      with:
        usesh: true
        run: package/compile && package/check

  compile-check-on-solaris:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: compile-check
      uses: vmactions/solaris-vm@v1
      with:
        release: "11.4-gcc"
        usesh: true
        run: |
          cp src/Makefile src/Makefile.old
          sed -e 's/ -static//' <src/Makefile.old >src/Makefile
          package/compile && package/check
